# Generated by Django 3.1.5 on 2021-01-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_induk', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=100)),
                ('pendidikan', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Krips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crips', models.IntegerField()),
                ('nilai', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_Kriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kriteria', models.CharField(max_length=2)),
                ('nama_kriteria', models.CharField(max_length=100)),
                ('attribut', models.CharField(choices=[('Cost', 'cost'), ('Benefit', 'benefit')], max_length=100)),
                ('bobot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_Nilai_Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dk1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dk1', to='nilai.data_krips')),
                ('dk2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dk2', to='nilai.data_krips')),
                ('dk3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dk3', to='nilai.data_krips')),
                ('dk4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dk4', to='nilai.data_krips')),
                ('dk5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dk5', to='nilai.data_krips')),
                ('dk6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dk6', to='nilai.data_krips')),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nilai.data_karyawan')),
            ],
        ),
        migrations.AddField(
            model_name='data_krips',
            name='kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nilai.data_kriteria'),
        ),
    ]
