# Generated by Django 3.1.5 on 2021-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_krips',
            name='crips',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data_kriteria',
            name='attribut',
            field=models.CharField(choices=[('cost', 'cost'), ('benefit', 'benefit')], max_length=100),
        ),
    ]
