# Generated by Django 3.1.5 on 2021-01-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0002_auto_20210117_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_krips',
            name='crips',
        ),
    ]
