# Generated by Django 3.1.5 on 2021-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0003_remove_data_krips_crips'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_nilai_karyawan',
            name='skor',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='dk1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='dk2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='dk3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='dk4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='dk5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='dk6',
            field=models.IntegerField(),
        ),
    ]
