# Generated by Django 3.1.5 on 2021-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0004_auto_20210117_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='skor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
