# Generated by Django 3.1.5 on 2021-01-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0005_auto_20210117_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_krips',
            name='nama_krips',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data_nilai_karyawan',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to='nilai.data_karyawan'),
        ),
    ]
