# Generated by Django 3.1.5 on 2021-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0006_auto_20210117_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='dk1',
        ),
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='dk2',
        ),
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='dk3',
        ),
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='dk4',
        ),
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='dk5',
        ),
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='dk6',
        ),
        migrations.AddField(
            model_name='data_nilai_karyawan',
            name='dk',
            field=models.ManyToManyField(to='nilai.Data_Krips'),
        ),
    ]
