# Generated by Django 3.1.5 on 2021-01-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0008_auto_20210117_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_kriteria',
            name='krips',
        ),
        migrations.AddField(
            model_name='data_kriteria',
            name='krips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nilai.data_krips'),
        ),
    ]
