# Generated by Django 3.1.5 on 2021-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0009_auto_20210117_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_kriteria',
            name='krips',
        ),
        migrations.AddField(
            model_name='data_kriteria',
            name='krips',
            field=models.ManyToManyField(to='nilai.Data_Krips'),
        ),
    ]
