# Generated by Django 3.1.5 on 2021-01-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0010_auto_20210117_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_krips',
            options={'ordering': ['nilai']},
        ),
        migrations.RemoveField(
            model_name='data_kriteria',
            name='krips',
        ),
        migrations.AddField(
            model_name='data_krips',
            name='kriteria',
            field=models.ManyToManyField(to='nilai.Data_Kriteria'),
        ),
    ]
