# Generated by Django 3.1.5 on 2021-01-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0011_auto_20210117_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='dk',
        ),
        migrations.AddField(
            model_name='data_nilai_karyawan',
            name='kriteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nilai.data_kriteria'),
        ),
        migrations.AddField(
            model_name='data_nilai_karyawan',
            name='nilai',
            field=models.IntegerField(null=True),
        ),
    ]
