# Generated by Django 3.1.5 on 2021-01-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0013_data_karyawan_skor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_nilai_karyawan',
            name='skor',
        ),
    ]
